name: algorithms
description: Practice from the Introduction to Algorithms book.
version: 1.0.0
repository: https://github.com/w3ggy/algorithms

environment:
  sdk: ^3.3.1

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
